#!/system/bin/sh
if [[ $1 = off ]]; then
cd '/data/local/bin/'
ifconfig wlan0 down
iwconfig wlan0 mode managed
ifconfig wlan0 up
elif [[ $1 = on ]]; then
cd '/data/wmon/'
sh 'setup.sh'
else
echo 'Wrong params. Use wmon [on] or [off].'
fi

